{% set name = "mpi4py" %}
{% set version = "3.1.0" %}
{% set sha256 = "134fa2b2fe6d8f91bcfcc2824cfd74b55ca3dcbff4d185b1bda009beea9232ec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win or py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  # TODO: build with msmpi when it works

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - {{ mpi }}
  run:
    - python
    - {{ mpi }}

test:
  files:
    - test_mpi.py

about:
  home: https://mpi4py.bitbucket.io/
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
    MPI for Python provides bindings of the Message Passing Interface (MPI)
    standard for the Python programming language, allowing any Python program
    to exploit multiple processors.
  doc_url: https://mpi4py.readthedocs.org/
  dev_url: https://bitbucket.org/mpi4py/mpi4py
